export const GET_ISSUES_SUCCESS = 'GET_ISSUES_SUCCES';
export const GET_ISSUES_FAIL = 'GET_ISSUES__FAIL ';

export const GET_ISSUE_SUCCESS = 'GET_ISSUE_SUCCES';
export const GET_ISSUE_FAIL = 'GET_ISSUE_FAIL ';

export const FILTER_ISSUES_SUCCESS = 'FILTER_ISSUES_SUCCESS';
export const FILTER_ISSUES_FAIL = 'FILTER_ISSUES_FAIL';

export const ADD_AUTHOR_FILTER = 'ADD_AUTHOR_FILTER';
export const ADD_STATUS_FILTER = 'ADD_STATUS_FILTER'
